# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from rpcz import service
from rpcz import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import calculator_pb2


_CALCULATORSERVICE = descriptor.ServiceDescriptor(
  name='CalculatorService',
  full_name='CalculatorService',
  file=calculator_pb2.DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=57,
  serialized_end=135,
  methods=[
  descriptor.MethodDescriptor(
    name='Add',
    full_name='CalculatorService.Add',
    index=0,
    containing_service=None,
    input_type=calculator_pb2._NUMBERS,
    output_type=calculator_pb2._NUMBERS,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Subtract',
    full_name='CalculatorService.Subtract',
    index=1,
    containing_service=None,
    input_type=calculator_pb2._NUMBERS,
    output_type=calculator_pb2._NUMBERS,
    options=None,
  ),
])

class CalculatorService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _CALCULATORSERVICE
class CalculatorService_Stub(CalculatorService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _CALCULATORSERVICE

